### ISSUE TITLE
无法正确获取Oracle Message内容

### ISSUE THREAD

**Issue by chenkangnhr** [wangqq1217/oracleAQ-Jms#1]
根据代码做了一个case，无法获取到正确的Oracle 入队的消息。
![微信截图_20221222221446](https://user-images.githubusercontent.com/56528016/209428736-2c50d2eb-35aa-41b0-b2d8-338d8d170dc7.png)

**Comment by wangqq1217** [comment]
chenkangnhr
        您好！我已收到您的邮件。
        关于这个问题，你可以检查一下自定义类TypeQueueMessage的 结构以及继承关系，和github中的对比一下，看看是否缺少了什么关键性的内容，尤其是重点看看自定义的getMessageContent方法；
        具体你可以断点看一下，TypeQueueMessage类中的那个数据属性，有没有值，如果有值的化，就说明监听没有问题，有问题的是你的getMessageContent方法；
       最后，如果一直调试不成功，方便的化可以把代码发我一下，我这边帮忙看看



        有什么问题随时与我联系和沟通，祝好！


2022-12-26
| |
王强强
***@***.***
|
---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2022年12月24日 17:03 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***> |
| 主题 | [wangqq1217/oracleAQ-Jms] 无法正确获取Oracle Message内容 (Issue #1) |

根据代码做了一个case，无法获取到正确的Oracle 入队的消息。

**Comment by chenkangnhr** [comment]
已经解决了，是我本地的数据库字符集问题，AQ是监听到了消息。非常感谢解答问题
